# Generated by Django 6.0.2 on 2026-06-05 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tasks', models.JSONField(default=list)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_targets',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
                ('current_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completed_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_entered_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_pending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('project_completion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('task_efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('growth_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_targets',
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
