# Generated by Django 6.0.2 on 2026-06-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], default='Active', max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_contact', models.CharField(blank=True, max_length=15)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_contact', models.CharField(blank=True, max_length=15)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('spouse_contact', models.CharField(blank=True, max_length=15)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_company', models.CharField(blank=True, max_length=100)),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_passbook', models.FileField(blank=True, null=True, upload_to='documents/bank/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='documents/aadhar/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/pan/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/resume/')),
                ('tenth_marksheet', models.FileField(blank=True, null=True, upload_to='documents/education/')),
                ('twelfth_marksheet', models.FileField(blank=True, null=True, upload_to='documents/education/')),
                ('graduation_marksheet', models.FileField(blank=True, null=True, upload_to='documents/education/')),
                ('post_graduation_marksheet', models.FileField(blank=True, null=True, upload_to='documents/education/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
